### ISSUE TITLE
User handling for OTC RDS

### ISSUE THREAD

**Issue by eumel8** [eumel8/otc-rds-operator#2]
Handling of database user and permission is not part of OTC API. only root user will be created on installation.
If we assume the Kubernetes Cluster has access to the RDS instance we can create user/databases from Operator.
There are enough [standard workflows](https://zetcode.com/golang/mysql/) for that.
CRD needs to be advanced:

```yaml
databases:
  - abc
  - cde
users:
  - name: uvw
     password: xxxx
  - name: xyz
     password: xxxx
privileges:
      - "GRANT SELECT ON abc.* TO 'xyz'@'10.0.0.0/24"
```

hint: Mysql? Postgresql?
password secret handling?
